Update CI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -154,127 +154,139 @@ build_images: &build_images
         paths:
           - "*"
 install_cluster: &install_cluster
-  run: |
-    cat \<< EOF | sed "s/172.18.0.2/$DEFAULT_DEX_IP/" | tee ./kubeapps-local-dev-apiserver-config.yaml
-    kind: Cluster
-    apiVersion: kind.x-k8s.io/v1alpha4
-    nodes:
-    - role: control-plane
-      kubeadmConfigPatches:
-      - |
-        kind: InitConfiguration
-        nodeRegistration:
-          kubeletExtraArgs:
-            node-labels: "ingress-ready=true"
-      - |
-        kind: ClusterConfiguration
-        apiServer:
-          extraArgs:
-            oidc-issuer-url: https://172.18.0.2:32000
-            oidc-client-id: default
-            oidc-ca-file: /etc/kubernetes/pki/apiserver.crt
-            oidc-username-claim: email
-            oidc-username-prefix: "oidc:"
-            oidc-groups-claim: groups
-            oidc-groups-prefix: "oidc:"
-      extraPortMappings:
-      - containerPort: 80
-        hostPort: 80
-        protocol: TCP
-      - containerPort: 443
-        hostPort: 443
-        protocol: TCP
-    EOF
-    {
-      echo "Creating cluster..."
-      kind create cluster --name kubeapps-ci --config=./kubeapps-local-dev-apiserver-config.yaml --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci --retain --wait 30s &&
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-users-rbac.yaml &&
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/ingress-nginx-kind-with-large-proxy-buffers.yaml &&
-      sleep 5 &&
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s &&
-      echo "Cluster created"
-    } || {
-      echo "Cluster creation failed, retrying..."
-      kind delete clusters kubeapps-ci || true
-      kind create cluster --name kubeapps-ci --config=./kubeapps-local-dev-apiserver-config.yaml --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci --retain --wait 30s || true &&
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-users-rbac.yaml &&
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/ingress-nginx-kind-with-large-proxy-buffers.yaml &&
-      sleep 5 &&
-      kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s &&
-      echo "Cluster created"
-    } || {
-      echo "Error while creating the cluster after retry"
-    }
+  run:
+    name: "Install cluster"
+    command:  |
+      cat \<< EOF | sed "s/172.18.0.2/$DEFAULT_DEX_IP/" | tee ./kubeapps-local-dev-apiserver-config.yaml
+      kind: Cluster
+      apiVersion: kind.x-k8s.io/v1alpha4
+      nodes:
+      - role: control-plane
+        kubeadmConfigPatches:
+        - |
+          kind: InitConfiguration
+          nodeRegistration:
+            kubeletExtraArgs:
+              node-labels: "ingress-ready=true"
+        - |
+          kind: ClusterConfiguration
+          apiServer:
+            extraArgs:
+              oidc-issuer-url: https://172.18.0.2:32000
+              oidc-client-id: default
+              oidc-ca-file: /etc/kubernetes/pki/apiserver.crt
+              oidc-username-claim: email
+              oidc-username-prefix: "oidc:"
+              oidc-groups-claim: groups
+              oidc-groups-prefix: "oidc:"
+        extraPortMappings:
+        - containerPort: 80
+          hostPort: 80
+          protocol: TCP
+        - containerPort: 443
+          hostPort: 443
+          protocol: TCP
+      EOF
+      {
+        echo "Creating cluster..."
+        kind create cluster --name kubeapps-ci --config=./kubeapps-local-dev-apiserver-config.yaml --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci --retain --wait 30s &&
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-users-rbac.yaml &&
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/ingress-nginx-kind-with-large-proxy-buffers.yaml &&
+        sleep 5 &&
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s &&
+        echo "Cluster created"
+      } || {
+        echo "Cluster creation failed, retrying..."
+        kind delete clusters kubeapps-ci || true
+        kind create cluster --name kubeapps-ci --config=./kubeapps-local-dev-apiserver-config.yaml --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci --retain --wait 30s || true &&
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-users-rbac.yaml &&
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/ingress-nginx-kind-with-large-proxy-buffers.yaml &&
+        sleep 5 &&
+        kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s &&
+        echo "Cluster created"
+      } || {
+        echo "Error while creating the cluster after retry"
+      }
 export_cluster_variables: &export_cluster_variables
-  run: |
-    export DEX_IP=`docker network inspect kind | jq '.[0].IPAM.Config[0].Gateway' | sed  's/"//g' | awk -F. '{ print $1"."$2"."$3"."$4+1 }'`
-    export ADDITIONAL_CLUSTER_IP=`docker network inspect kind | jq '.[0].IPAM.Config[0].Gateway' | sed  's/"//g' | awk -F. '{ print $1"."$2"."$3"."$4+2 }'`
-    
-    echo DEFAULT_DEX_IP=$DEFAULT_DEX_IP
-    echo DEX_IP=$DEX_IP
-    echo ADDITIONAL_CLUSTER_IP=$ADDITIONAL_CLUSTER_IP
+  run:
+    name: "Export cluster variables"
+    command:  |
+      export DEX_IP=`docker network inspect kind | jq '.[0].IPAM.Config[0].Gateway' | sed  's/"//g' | awk -F. '{ print $1"."$2"."$3"."$4+1 }'`
+      export ADDITIONAL_CLUSTER_IP=`docker network inspect kind | jq '.[0].IPAM.Config[0].Gateway' | sed  's/"//g' | awk -F. '{ print $1"."$2"."$3"."$4+2 }'`
+      
+      echo DEFAULT_DEX_IP=$DEFAULT_DEX_IP
+      echo DEX_IP=$DEX_IP
+      echo ADDITIONAL_CLUSTER_IP=$ADDITIONAL_CLUSTER_IP
 
-    # If running kubectl without args, use the default "kubeapps-ci" cluster
-    cp ${HOME}/.kube/kind-config-kubeapps-ci ${HOME}/.kube/config
-    kubectl config set-context kind-kubeapps-ci 
-    kubectl get pods
+      # If running kubectl without args, use the default "kubeapps-ci" cluster
+      cp ${HOME}/.kube/kind-config-kubeapps-ci ${HOME}/.kube/config
+      kubectl config set-context kind-kubeapps-ci 
+      kubectl get pods
 
-    # If the default IP the proper one, the multicluster setup will fail
-    if [ "$DEFAULT_DEX_IP" != "$DEX_IP" ]; then echo "Default IP does not match with current IP used in Kind"; exit 1; fi
+      # If the default IP the proper one, the multicluster setup will fail
+      if [ "$DEFAULT_DEX_IP" != "$DEX_IP" ]; then echo "Default IP does not match with current IP used in Kind"; exit 1; fi
 install_additional_cluster: &install_additional_cluster
-  run: |
-    {
-      echo "Creating additional cluster..."
-      kind create cluster --name kubeapps-ci-additional --config=./docs/user/manifests/kubeapps-local-dev-additional-apiserver-config.yaml --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional --retain --wait 10s &&
-      kubectl --context kind-kubeapps-ci-additional --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci-additional apply --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-users-rbac.yaml &&
-      kubectl --context kind-kubeapps-ci-additional --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci-additional apply --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-namespace-discovery-rbac.yaml &&
-        echo "Additional cluster created"
-    } || {
-        echo "Additional cluster creation failed, retrying..."
-        kind delete clusters kubeapps-ci-additional || true
+  run:
+    name: "Install additional cluster"
+    command:  |
+      {
+        echo "Creating additional cluster..."
         kind create cluster --name kubeapps-ci-additional --config=./docs/user/manifests/kubeapps-local-dev-additional-apiserver-config.yaml --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional --retain --wait 10s &&
-      kubectl --context kind-kubeapps-ci-additional --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci-additional apply --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-users-rbac.yaml &&
-      kubectl --context kind-kubeapps-ci-additional --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci-additional apply --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-namespace-discovery-rbac.yaml &&
-        echo "Additional cluster created"
-    } || {
-        echo "Error while creating the additional cluster after retry"
-    }
+        kubectl --context kind-kubeapps-ci-additional --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci-additional apply --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-users-rbac.yaml &&
+        kubectl --context kind-kubeapps-ci-additional --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci-additional apply --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-namespace-discovery-rbac.yaml &&
+          echo "Additional cluster created"
+      } || {
+          echo "Additional cluster creation failed, retrying..."
+          kind delete clusters kubeapps-ci-additional || true
+          kind create cluster --name kubeapps-ci-additional --config=./docs/user/manifests/kubeapps-local-dev-additional-apiserver-config.yaml --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional --retain --wait 10s &&
+        kubectl --context kind-kubeapps-ci-additional --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci-additional apply --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-users-rbac.yaml &&
+        kubectl --context kind-kubeapps-ci-additional --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci-additional apply --kubeconfig=${HOME}/.kube/kind-config-kubeapps-ci-additional -f https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/user/manifests/kubeapps-local-dev-namespace-discovery-rbac.yaml &&
+          echo "Additional cluster created"
+      } || {
+          echo "Error while creating the additional cluster after retry"
+      }
 install_olm: &install_olm
-  run: |
-    # Operators are not supported in GKE 1.14 and flaky in 1.15
-    if [[ -z "${GKE_BRANCH-}" ]]; then
-      echo "Installing OLM ${OLM_VERSION} ..."
-      url=https://github.com/operator-framework/operator-lifecycle-manager/releases/download/${OLM_VERSION}
+  run:
+    name: "Install OLM"
+    command:  |
+      # Operators are not supported in GKE 1.14 and flaky in 1.15
+      if [[ -z "${GKE_BRANCH-}" ]]; then
+        echo "Installing OLM ${OLM_VERSION} ..."
+        url=https://github.com/operator-framework/operator-lifecycle-manager/releases/download/${OLM_VERSION}
 
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f ${url}/crds.yaml 
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f ${url}/olm.yaml 
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f ${url}/crds.yaml 
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci apply -f ${url}/olm.yaml 
 
-      # wait for deployments to be ready
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci  wait --namespace olm --for=condition=available  --timeout=60s deployment/catalog-operator
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci  wait --namespace olm --for=condition=available  --timeout=60s deployment/olm-operator
-      kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci  wait --namespace olm --for=condition=available  --timeout=60s deployment/packageserver
-    fi
+        # wait for deployments to be ready
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci  wait --namespace olm --for=condition=available  --timeout=60s deployment/catalog-operator
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci  wait --namespace olm --for=condition=available  --timeout=60s deployment/olm-operator
+        kubectl --context kind-kubeapps-ci --kubeconfig ${HOME}/.kube/kind-config-kubeapps-ci  wait --namespace olm --for=condition=available  --timeout=60s deployment/packageserver
+      fi
 install_kubectl: &install_kubectl
-  run: |
-    curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl
-    chmod +x ./kubectl
-    sudo mv ./kubectl /usr/local/bin/kubectl
+  run:
+    name: "Install kubectl"
+    command:  |
+      curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
+      chmod +x ./kubectl
+      sudo mv ./kubectl /usr/local/bin/kubectl
 run_e2e_tests: &run_e2e_tests
-  run: |
-    # If we want to test the latest version instead we override the image to be used
-    if [[ -n "$TEST_LATEST_RELEASE" ]]; then
-      source ./script/chart_sync_utils.sh
-      latest=$(latestReleaseTag)
-      DEV_TAG=${latest/v/}
-      IMG_MODIFIER=""
-    fi
-    if ./script/e2e-test.sh $DEV_TAG $IMG_MODIFIER $DEX_IP; then
-      # Test success
-      echo "export TEST_RESULT=$?" >> $BASH_ENV
-    else
-      # Test failed
-      echo "export TEST_RESULT=$?" >> $BASH_ENV
-    fi
+  run:
+    name: "Run e2e tests script"
+    command:  |
+      # If we want to test the latest version instead we override the image to be used
+      if [[ -n "$TEST_LATEST_RELEASE" ]]; then
+        source ./script/chart_sync_utils.sh
+        latest=$(latestReleaseTag)
+        DEV_TAG=${latest/v/}
+        IMG_MODIFIER=""
+      fi
+      if ./script/e2e-test.sh $DEV_TAG $IMG_MODIFIER $DEX_IP; then
+        # Test success
+        echo "export TEST_RESULT=$?" >> $BASH_ENV
+      else
+        # Test failed
+        echo "export TEST_RESULT=$?" >> $BASH_ENV
+      fi
 gke_test: &gke_test
   docker:
     - image: circleci/golang:1.16
@@ -325,25 +337,32 @@ local_e2e_steps: &local_e2e_steps
     - checkout
     - <<: *exports
     # Install kind
-    - run: |
-        curl -LO https://github.com/kubernetes-sigs/kind/releases/download/v0.10.0/kind-Linux-amd64
-        chmod +x kind-Linux-amd64
-        sudo mv kind-Linux-amd64 /usr/local/bin/kind
+    - run:
+        name: "Install kind"
+        command:  |
+          curl -LO https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-Linux-amd64
+          chmod +x kind-Linux-amd64
+          sudo mv kind-Linux-amd64 /usr/local/bin/kind
     - <<: *install_kubectl
     # Create the "kubeapps-ci" cluster and configure it to use dex (for the OIDC authentication)
     - <<: *install_cluster
     # dex will be running on the same node as the API server in the dev environment, so we can reuse the key and cert from the apiserver
-    - run: |
-        docker cp kubeapps-ci-control-plane:/etc/kubernetes/pki/apiserver.crt ./devel/dex.crt
-        docker cp kubeapps-ci-control-plane:/etc/kubernetes/pki/apiserver.key ./devel/dex.key
+    - run:
+        name: "Copy apiserver certificates"
+        command:  |
+          docker cp kubeapps-ci-control-plane:/etc/kubernetes/pki/apiserver.crt ./devel/dex.crt
+          docker cp kubeapps-ci-control-plane:/etc/kubernetes/pki/apiserver.key ./devel/dex.key
     # Create the "kubeapps-ci-additional" cluster
     # - <<: *install_additional_cluster
     # Export variables and kubeconfig 
     - <<: *export_cluster_variables
-    - run: |
-        curl -LO https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
-        chmod +x mkcert-v1.4.3-linux-amd64
-        sudo mv mkcert-v1.4.3-linux-amd64 /usr/local/bin/mkcert
+    - run:
+        name: "Install mkcert"
+        command:  |
+          curl -LO "https://github.com/FiloSottile/mkcert/releases/download/${MKCERT_VERSION}/mkcert-${MKCERT_VERSION}-linux-amd64"
+          chmod +x "mkcert-${MKCERT_VERSION}-linux-amd64"
+          sudo mv "mkcert-${MKCERT_VERSION}-linux-amd64" /usr/local/bin/mkcert
+          mkcert -install
     - <<: *install_helm_cli
     # Load images from other jobs
     # - attach_workspace:
@@ -433,6 +452,9 @@ jobs:
       TEST_UPGRADE: "1"
       DEFAULT_DEX_IP: "172.18.0.2"
       OLM_VERSION: "v0.17.0"
+      MKCERT_VERSION: "v1.4.3"
+      KUBECTL_VERSION: "v1.20.5"
+      KIND_VERSION: "v0.10.0"
     parameters:
       number:
         type: string
