Extract gke_e2e_tests reusable workflow
Signed-off-by: Jesús Benito Calzada <bjesus@vmware.com>

diff --git a/.github/workflows/kubeapps.yaml b/.github/workflows/kubeapps.yaml
--- a/.github/workflows/kubeapps.yaml
+++ b/.github/workflows/kubeapps.yaml
@@ -648,8 +648,8 @@ jobs:
               ${DEV_MODE}
 
   GKE_REGULAR_VERSION_MAIN:
-#    TODO:
-#    <<: *build_on_tag_or_prerelease
+    #    TODO:
+    #    <<: *build_on_tag_or_prerelease
     if: needs.setup.outputs.triggered_from_fork == 'false'
     needs:
       - setup
@@ -662,71 +662,105 @@ jobs:
       - build_e2e_runner_image
       # FIXME: sync_chart_from_bitnami disabled for development as it only runs in main branch, uncomment before merging
 #      - sync_chart_from_bitnami
-    runs-on: ubuntu-latest
-    env:
-      USE_MULTICLUSTER_OIDC_ENV: "false"
-      TEST_TIMEOUT_MINUTES: 6
+    uses: ./.github/workflows/gke_e2e_tests.yaml
+    with:
+      ID: "regular_version_main"
+      GKE_BRANCH: ${GKE_BRANCH}
+      GKE_CLUSTER: ${GKE_CLUSTER}
+      GKE_PROJECT: ${GKE_PROJECT}
+      GKE_ZONE: ${GKE_ZONE}
+      HELM_VERSION_MIN: ${HELM_VERSION_MIN}
+      HELM_VERSION_STABLE: ${HELM_VERSION_STABLE}
+      KUBECTL_VERSION: ${KUBECTL_VERSION}
+      TEST_TIMEOUT_MINUTES: ${TEST_TIMEOUT_MINUTES}
+      TEST_LATEST_RELEASE: ${TEST_LATEST_RELEASE}
+      USE_MULTICLUSTER_OIDC_ENV: ${USE_MULTICLUSTER_OIDC_ENV}
+      DEBUG_MODE: ${DEBUG_MODE}
+      DEV_MODE: ${DEV_MODE}
+    secrets:
       GKE_ADMIN: ${{ secrets.GKE_ADMIN }}
       GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
-      DEBUG_MODE: true
-    steps:
-      - # We need this step because we can not set a env var taking the value from another existing env var via the job.<id>.env section
-        name: Set GKE_BRANCH
-        run: |
-          set -eu
-          echo "GKE_BRANCH=${GKE_REGULAR_VERSION}" >> ${GITHUB_ENV}
-      - uses: actions/checkout@v3
-#      - name: Check conditions
+
+#  GKE_REGULAR_VERSION_MAIN:
+##    TODO:
+##    <<: *build_on_tag_or_prerelease
+#    if: needs.setup.outputs.triggered_from_fork == 'false'
+#    needs:
+#      - setup
+#      - test_go
+#      - test_dashboard
+#      - test_pinniped_proxy
+#      - test_chart_render
+#      - build_docker_images
+#      - build_dashboard_image
+#      - build_e2e_runner_image
+#      # FIXME: sync_chart_from_bitnami disabled for development as it only runs in main branch, uncomment before merging
+##      - sync_chart_from_bitnami
+#    runs-on: ubuntu-latest
+#    env:
+#      USE_MULTICLUSTER_OIDC_ENV: "false"
+#      TEST_TIMEOUT_MINUTES: 6
+#      GKE_ADMIN: ${{ secrets.GKE_ADMIN }}
+#      GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
+#      DEBUG_MODE: true
+#    steps:
+#      - # We need this step because we can not set a env var taking the value from another existing env var via the job.<id>.env section
+#        name: Set GKE_BRANCH
 #        run: |
-#          source ./script/chart_sync_utils.sh
+#          set -eu
+#          echo "GKE_BRANCH=${GKE_REGULAR_VERSION}" >> ${GITHUB_ENV}
+#      - uses: actions/checkout@v3
+##      - name: Check conditions
+##        run: |
+##          source ./script/chart_sync_utils.sh
+##
+##          # In the case of GKE we will only want to build if it is
+##          # a build of a branch in the kubeapps repository
+##          if [[ -z "$GKE_ADMIN" ]]; then
+##            echo "Step cancelled, we are not in the Kubeapps repository"
+##            circleci step halt
+##          fi
+##
+##          # Cancel job if this is a test stable release job but
+##          # the chart version has not been bumped
+##          if [[ -n "${TEST_LATEST_RELEASE:-}" ]] && ! changedVersion; then
+##            echo "Step cancelled, we are not releasing a new version of the chart"
+##            circleci step halt
+##          fi
+#      - run: |
+#          set -euo pipefail
+#          source ./script/lib/libcitools.sh
 #
-#          # In the case of GKE we will only want to build if it is
-#          # a build of a branch in the kubeapps repository
-#          if [[ -z "$GKE_ADMIN" ]]; then
-#            echo "Step cancelled, we are not in the Kubeapps repository"
-#            circleci step halt
-#          fi
+#          installGCloudSDK
+#          configureGCloud ${GKE_PROJECT} ${GCLOUD_KEY}
+#          installKubectl ${KUBECTL_VERSION}
+#          installHelm ${HELM_VERSION_MIN}
+#          installHelm ${HELM_VERSION_STABLE} helm-stable
+#          exportEscapedGKEClusterName "${GKE_CLUSTER}" "${GKE_BRANCH}" "${GITHUB_REF_NAME}" "${TEST_LATEST_RELEASE:-0}" "${DEV_MODE}"
+#      - name: Start GKE environment
+#        run: |
+#          set -euo pipefail
 #
-#          # Cancel job if this is a test stable release job but
-#          # the chart version has not been bumped
-#          if [[ -n "${TEST_LATEST_RELEASE:-}" ]] && ! changedVersion; then
-#            echo "Step cancelled, we are not releasing a new version of the chart"
-#            circleci step halt
-#          fi
-      - run: |
-          set -euo pipefail
-          source ./script/lib/libcitools.sh
-
-          installGCloudSDK
-          configureGCloud ${GKE_PROJECT} ${GCLOUD_KEY}
-          installKubectl ${KUBECTL_VERSION}
-          installHelm ${HELM_VERSION_MIN}
-          installHelm ${HELM_VERSION_STABLE} helm-stable
-          exportEscapedGKEClusterName "${GKE_CLUSTER}" "${GKE_BRANCH}" "${GITHUB_REF_NAME}" "${TEST_LATEST_RELEASE:-0}" "${DEV_MODE}"
-      - name: Start GKE environment
-        run: |
-          set -euo pipefail
-
-          ./script/start-gke-env.sh $ESCAPED_GKE_CLUSTER $GKE_ZONE $GKE_BRANCH $GKE_ADMIN > /dev/null
-      - # TODO(castelblanque) Unify shared resources with kubeapps-local-dev-users-rbac.yaml that only applies to Kind clusters
-        name: Apply customizations to GKE cluster
-        run: |
-          kubectl create namespace kubeapps-user-namespace
-          ./script/install-nginx.sh
-      - name: "Run e2e tests script"
-        env:
-          TESTS_GROUP: "all"
-        run: ./script/run_e2e_tests.sh
-      - name: 'Upload Artifacts'
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: gke_regular_version_e2e_tests_reports
-          path: integration/reports
-      - name: "Delete GKE cluster"
-        if: always()
-        run: |
-          set -euo pipefail
-          source ./script/lib/libcitools.sh
-          
-          deleteGKECluster $GKE_ZONE $ESCAPED_GKE_CLUSTER
+#          ./script/start-gke-env.sh $ESCAPED_GKE_CLUSTER $GKE_ZONE $GKE_BRANCH $GKE_ADMIN > /dev/null
+#      - # TODO(castelblanque) Unify shared resources with kubeapps-local-dev-users-rbac.yaml that only applies to Kind clusters
+#        name: Apply customizations to GKE cluster
+#        run: |
+#          kubectl create namespace kubeapps-user-namespace
+#          ./script/install-nginx.sh
+#      - name: "Run e2e tests script"
+#        env:
+#          TESTS_GROUP: "all"
+#        run: ./script/run_e2e_tests.sh
+#      - name: 'Upload Artifacts'
+#        if: failure()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: gke_regular_version_e2e_tests_reports
+#          path: integration/reports
+#      - name: "Delete GKE cluster"
+#        if: always()
+#        run: |
+#          set -euo pipefail
+#          source ./script/lib/libcitools.sh
+#
+#          deleteGKECluster $GKE_ZONE $ESCAPED_GKE_CLUSTER
